project:
  type: book
  output-dir: output/reports

book: 
  title: "Online Machine Learning com Aplicações em R"
  author: "João Paulo Assis Bonifácio"
  date: today
  date-format: long
  cover-image: "images/cover.png"
  chapters:
    - index.qmd

    - part: "Parte 1"
    - chapters/01-introducao.qmd

format:
  html:
    theme: default
    toc: true
    number-sections: true
    css: styles.css
  pdf:
    documentclass: scrreprt

bibliography: references.bib
lang: pt
