project:
  type: book
  output-dir: output/reports

book: 
  title: "Online Machine Learning com Aplicações em R"
  author: "Rafael de Souza"
  date: "2025"
  chapters:
    - index.qmd
    - chapters/01-introducao.qmd

format:
  html:
    theme: default
    toc: true
    number-sections: true
    css: styles.css
  pdf:
    documentclass: scrreprt

bibliography: references.bib
lang: pt
